// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYYsghqa0PLXQB-kiBRLYSbnET5NWuD4',
    appId: '1:40343468216:android:ca2792dddda03d0dc81c4d',
    messagingSenderId: '40343468216',
    projectId: 'neu-fall-2022',
    databaseURL: 'https://neu-fall-2022-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMCdgzeAen_KUk0SoXOxw_Q0jOcIl86w',
    appId: '1:40343468216:ios:8f557812cf6bfd24c81c4d',
    messagingSenderId: '40343468216',
    projectId: 'neu-fall-2022',
    databaseURL: 'https://neu-fall-2022-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2022.appspot.com',
    androidClientId: '40343468216-0f440oq3sei7390pr2hnr7bigrti18rr.apps.googleusercontent.com',
    iosClientId: '40343468216-50sd6dekoo2qontcbopfa1lt751o7jf3.apps.googleusercontent.com',
    iosBundleId: 'mobile.final',
  );
}
